### ISSUE TITLE
launchWebAuthFlow origin

### ISSUE THREAD

**Issue by yathit** [operasoftware/devopera#486]
What is origin for [launchWebAuthFlow redirect]((https://developer.chrome.com/apps/identity#method-launchWebAuthFlow))? For chrome it is `https://<app-id>.chromiumapp.org/*`.

**Comment by pepelsbey** [comment]
This repository’s issues are used for Dev.Opera source code and articles only. But you can ask @shwetank regarding extensions.

**Comment by shwetank** [comment]
If there are any bugs or scope for improvement in the documentation, then this is the right place. Otherwise, as vadim mentioned, it is better to ask it on the [forums](https://forums.opera.com/categories/en-opera-add-ons). 

Btw, I'll be confirming the answer to your question soon. I request you to please ask this on the forums, and I'll reply to you there.

**Comment by yathit** [comment]
Thanks. I will post in forum when I receive password reset email.

On Thu, Jul 7, 2016 at 4:48 PM, Shwetank Dixit <notifications@github.com>
wrote:

> If there are any bugs or scope for improvement in the documentation, then
> this is the right place. Otherwise, as vadim mentioned, it is better to ask
> it on the forums <https://forums.opera.com/categories/en-opera-add-ons>.
>
> Btw, I'll be confirming the answer to your question soon. I request you to
> please ask this on the forums, and I'll reply to you there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/operasoftware/devopera/issues/486#issuecomment-231019746>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACCfTNpNn9eC7smDMZ0HCzJ6Q7cGVXdIks5qTL1egaJpZM4JGrjC>
> .
>



-- 
Best regards,
Kyaw
